name: Build with MSBuild(test)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build x86 and x64
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2

      - name: Build x86
        run: |
          msbuild steamcloud.sln /p:Configuration=Release /p:Platform=x86

      - name: Show x86 build output files
        run: |
          Get-ChildItem -Recurse -File | ForEach-Object { $_.FullName }

      - name: Upload x86 Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-x86
          path: |
            **\x86\Release\*.exe

      - name: Build x64
        run: |
          msbuild steamcloud.sln /p:Configuration=Release /p:Platform=x64

      - name: Show x64 build output files
        run: |
          Get-ChildItem -Recurse -File | ForEach-Object { $_.FullName }

      - name: Upload x64 Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-x64
          path: |
            **\x64\Release\*.exe
