name: Build & Release Steamcloud (Backend)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || github.event.release.target_commitish == 'backend'
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Win32 (x86)
        run: msbuild steamcloud.sln /p:Configuration=Release /p:Platform=x86

      - name: Build x64
        run: msbuild steamcloud.sln /p:Configuration=Release /p:Platform=x64

      - name: Pack x86 to RAR
        shell: cmd
        run: '"./utils/rar.exe" a steamcloud-x86.rar "output\Win32\Release\steamcloud.exe"'

      - name: Pack x64 to RAR
        shell: cmd
        run: '"./utils/rar.exe" a steamcloud-x64.rar "output\x64\Release\steamcloud.exe"'

      - name: Upload artifact (manual run only)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: steamcloud-builds
          path: |
            steamcloud-x86.rar
            steamcloud-x64.rar

      - name: Upload to GitHub Release (release trigger only)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            steamcloud-x86.rar
            steamcloud-x64.rar
